using System;
using System.Collections.Generic;

namespace Project_Euler_Tasks
{
    public class Task2 : ITask
    {
        public int TaskID { get; } = 2;

        public ITask ShowInfo()
        {
            Console.WriteLine("Even Fibonacci Numbers:");
            Console.WriteLine("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:");
            Console.WriteLine();
            Console.WriteLine("1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...");
            Console.WriteLine();
            Console.WriteLine("By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.");
            Console.WriteLine();
            return this;
        }

        public void Run()
        {
            List<long> fibList = new List<long>() { 1, 2 };
            long nextInLine = 0;
            long sum = 0;

            for (long i = 0; i < 4000000; i++)
            {
                nextInLine = fibList[fibList.Count - 1] + fibList[fibList.Count - 2];
                fibList.Add(nextInLine);

                if (fibList[Convert.ToInt32(i)] % 2 == 0)
                    sum += nextInLine;
            }

            Console.WriteLine("Sum of all even nums in a fib seq upto 4million is:");
            Console.WriteLine(sum);
        }
    }
}
